### PR TITLE
Add an option to set minSdkVersion for android compile

### PR DESCRIPTION
**Pull request by am**
Hopefully this fixes https://github.com/bamlab/fastlane-plugin-cordova/issues/18.
I'll try to test this on my end, but it would be nice if someone could take a look into it.

Thanks

### CODE REVIEW

**Comment by Almouro** [comment]
Hi @am, 
Thanks for the PR, this looks good. Can you test that this fixes your issue?
You should be able to install a plugin from relative path with Fastlane.

**Comment by am** [comment]
@Almouro sorry for the delay here. I'm currently testing this. I can tell that setting the version works. I've noticed that I miss-understood the default value, so there is a last commit to address that.

When all checks pass from my side I'll leave a note here, and hopefully we can integrate this into the plugin.

Thank you

**Comment by am** [comment]
I've a green light from my side. All builds are passing using this branch. I've different lanes one uses `min_sdk_version` and other that does not. Both build correctly. When the `min_sdk_version` is not set it defaults to the value in the `config.xml`.

From my end I would be glad to see this merged.

**Comment by Almouro** [comment]
Awesome, thanks @am! Now merged and published :)

**Pull request merged**
